version: "3.7"
services:
  myapp-frontend:
    build:
      context: ./frontend
    image: devanshagrawal/myapp-frontend:2.0
    environment:
      BACKENDLB: myapp-backend
    ports:
      - "9000:80"
    volumes:
      - type: volume
        source: myapp-frontend-logval
        target: /var/log
  myapp-backend:
    build:
      context: ./backend
    image: devanshagrawal/myapp-backend:2.0
    depends_on:
      - myapp-frontend
    volumes:
      - type: volume
        source: myapp-backend-logval
        target: /var/log
  myapp-db:
    image: mysql:5.7
    volumes:
      - type: volume
        source: myapp-db-vol
        target: /var/log/mysql
        read_only: true
volumes: 
  myapp-frontend-logval:
  myapp-backend-logval:
  myapp-db-vol:
